# Generated by Django 5.2.8 on 2026-01-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0005_loginattempt_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['-login_time']},
        ),
    ]
